services:
  freeipa:
    image: freeipa/freeipa-server:almalinux-10
    container_name: freeipa-server
    hostname: auth-tmatch.isc-vs.dev
    tty: true
    stdin_open: true

    privileged: false

    environment:
      - IPA_SERVER_HOSTNAME=${IPA_SERVER_HOSTNAME}
      - PASSWORD=${IPA_PASSWORD}

    volumes:
      - ./srv/freeipa-data:/data:Z

    tmpfs:
      - /run
      - /tmp

    ports:
      - "12343:443"
      - "12389:389"
      - "12336:636"

    command:
      - ipa-server-install
      - -U
      - -r
      - TMATCH.ISC-VS.DEV
      - --domain
      - tmatch.isc-vs.dev
      - --no-ntp
      - --no-host-dns
      - --skip-mem-check

    restart: unless-stopped

  tmatch_db:
    image: postgres:16-alpine
    container_name: tmatch_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "3132:5432"
    restart: unless-stopped
    volumes:
      - ./srv/tmatch_db_data:/var/lib/postgresql/data

  tmatch_app:
    build: .
    container_name: tmatch_app
    restart: unless-stopped
    environment:
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_BASE_DN=${LDAP_BASE_DN}

      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

      - DB_NAMe=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8084:8501"
    depends_on:
      - tmatch_db
      - freeipa
    volumes:
      - ./srv/tmatch_specs_data:/app/specs

volumes:
   tmatch_specs_data:
   tmatch_db_data:
   tmatch_keycloak_data:
