"""Project per program

Revision ID: 31bc8bdf4d6a
Revises: 39566c1170e0
Create Date: 2026-04-27 14:03:50.301600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bc8bdf4d6a'
down_revision: Union[str, Sequence[str], None] = '39566c1170e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('program_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'programs', ['program_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'program_id')
    # ### end Alembic commands ###
